spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:jstqb-quiz}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}

    