spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:jstqb-quiz}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  file:
    name: ${LOG_FILE_NAME:jstqb-quiz.log}